"""VectorUpserter: convert ChunkRecords to VectorRecords and upsert into VectorStore.

Accepts ChunkRecords produced by DenseEncoder (dense_vector must be set),
converts them to VectorRecord objects, and calls BaseVectorStore.upsert().

Idempotency is guaranteed by the deterministic chunk IDs already embedded in
ChunkRecord (generated by DocumentChunker as {doc_id}_{index:04d}_{hash_8}).
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from core.types import ChunkRecord
from libs.vector_store.base_vector_store import VectorRecord
from libs.vector_store.vector_store_factory import VectorStoreFactory

if TYPE_CHECKING:
    from libs.vector_store.base_vector_store import BaseVectorStore
    from core.settings import Settings


class VectorUpserter:
    """Write dense-encoded ChunkRecords into a VectorStore backend.

    Typical usage::

        upserter = VectorUpserter(settings)
        upserter.upsert(records)          # idempotent, ordered
    """

    def __init__(
        self,
        settings: "Settings",
        vector_store: "BaseVectorStore | None" = None,
    ) -> None:
        self._store = vector_store or VectorStoreFactory.create(settings.vector_store)

    def upsert(self, records: list[ChunkRecord], trace: Any | None = None) -> None:
        """Convert ChunkRecords to VectorRecords and upsert into the vector store.

        Args:
            records: ChunkRecords with dense_vector populated by DenseEncoder.
            trace: Optional TraceContext (Phase F).

        Raises:
            ValueError: if any record is missing dense_vector.
        """
        if not records:
            return

        missing = [r.id for r in records if r.dense_vector is None]
        if missing:
            raise ValueError(
                f"ChunkRecords missing dense_vector (run DenseEncoder first): {missing[:5]}"
            )

        vector_records = [
            VectorRecord(
                id=record.id,
                vector=record.dense_vector,  # type: ignore[arg-type]
                text=record.text,
                metadata=dict(record.metadata),
            )
            for record in records
        ]

        self._store.upsert(vector_records, trace=trace)
